[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$nHrhIJKm$o14qVTgU0lzD68XLIkJXX/"
  ]

[http.routers.api]
  rule = "Host(`traefik.proietti.net`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
